spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coordinatoor
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    context-path: /api
